
version: "3.4"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend_dosug.entrypoints=https"
      - "traefik.http.routers.frontend_dosug.rule=Host(`dosugrostov.site`)"
      - "traefik.http.routers.frontend_dosug.tls=true"
      - "traefik.http.routers.frontend_dosug.tls.certresolver=letsEncrypt"
    networks:
      - web
    ports:
      - "8080:8080"
    restart: always

networks:
  web:
    external: true
