version: "3.4"

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile

    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend_dosug.entrypoints=https"
      - "traefik.http.routers.frontend_dosug.rule=Host(`dosugrostov.site`)"
      - "traefik.http.routers.frontend_dosug.tls=true"
      - "traefik.http.routers.frontend_dosug.tls.certresolver=letsEncrypt"
    networks:
      - web
    ports:
      - '8080:8080'

  # frontend_admin:
  #   build:
  #     context: .
  #     dockerfile: Dockerfile
  #   labels:
  #     - "traefik.enable=true"
  #     - "traefik.http.routers.frontend_admin_dosug.entrypoints=https"
  #     # 1257351904
  #     # || PathPrefix(`/adminQuestionnairePage/[0-9]+$$`)
  #     - "traefik.http.routers.frontend_admin_dosug.rule=Host(`dosugrostov.site`)  || PathPrefix(`/adminQuestionnairePage/*`)"
  #     # && (PathRegexp(`/adminQuestionnairePage/[0-9]+$`))   {id:[0-9]+}
  #     - "traefik.http.middlewares.traefik-admin.stripprefix.prefixes=/adminQuestionnairePage/*"
  #     # - "traefik.http.middlewares.traefik-admin.headers.accesscontrolalloworiginlist='*'"
  #     # - "traefik.http.middlewares.portainer-trailingslash.replacepathregex.regex=^/adminQuestionnairePage(.*)"
  #     # - "traefik.http.middlewares.portainer-trailingslash.replacepathregex.replacement=/adminQuestionnairePage/$$1"
  #     - "traefik.http.routers.frontend_admin_dosug.middlewares=traefik-admin"

  #     # - "traefik.http.middlewares.traefik-admin.replacepathregex.regex=^/adminQuestionnairePage/(.*)"

  #     - "traefik.http.routers.frontend_admin_dosug.tls=true"
  #     - "traefik.http.routers.frontend_admin_dosug.tls.certresolver=letsEncrypt"
      
    # networks:
    #   - web
    # # volumes:
    # # - "../pkg/images/:/app/pkg/images/"
    #   # - '.:/app'
    #   # - '/app/node_modules'
    # ports:
    #   - '8082:8080'
networks:
  web:
    external: true
  

